/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz4a;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {


    //ตัวอย่าง 1 ให้สร้าง Employee Employee(1, "John Doe", 50000) และตรวจสอบว่าเงินเดือน เป็น 50000
    @Test 
        void createEmployee() {
        Employee emp = new Employee(1,"john Doe", null, 50000);
        assertEquals(1,emp.getEmployeeId());
        assertEquals("John Doe",emp.getName());
        assertEquals(50000,emp.getcalculateSalary());

    }
ฆ
    //ข้อ 2 ตรวจสอบว่า Salary ตั้งให้ติดลบไม่ได้
    @Test 
    void SalaryCannotBeNegative() {
    Employee emp =new Employee(2,"Jane Doe",-10000);
    assertEquals(0,emp.calculateSalary());//มีค่าเป็นศูนย์
    }

    //ข้อ 3 ตรวจสอบว่า Bonus เป็น 20% ของ เงินเดือน(Salary)
    //ต้องมีการแก้ไข code ใน Manager.java ให้ถูกต้อง
    @Test 
    void Bonus20() {
        Manager manager = new Manager(3,"Alice Smith",50000,"IT",10000);
        double expectedSalaryWithBonus = 50000 + (5000 * 0.2);
        assertEquals(expectedSalaryWithBonus,manager.calculateSalary());
        
    }
}
//ทดสอบว่าโบนัสเป็น20เปอร์เซนต์ของเงินเดือน ต้องแก้ไข Manager.java ให้ calculateSalary() คำนวณ รวมโบนัส